""" made KyleCart table

Revision ID: 2526d9e44a2b
Revises: 62ece9f9eea8
Create Date: 2023-03-05 14:56:30.844201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2526d9e44a2b'
down_revision = '62ece9f9eea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyle_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kyle_id'], ['kyle_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyle_carts')
    # ### end Alembic commands ###
