"""add kyle_logs table

Revision ID: 3b7337331f37
Revises: 62ece9f9eea8
Create Date: 2023-03-07 11:31:50.719369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7337331f37'
down_revision = '62ece9f9eea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('kyle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyle_id', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_entry', sa.String(), nullable=True),
    sa.Column('date_of_adoption', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kyle_id'], ['kyle_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyle_logs')
    # ### end Alembic commands ###
