"""__repr__ for kyle_items

Revision ID: 62ece9f9eea8
Revises: ec00b5636e94
Create Date: 2023-03-07 10:18:55.974508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ece9f9eea8'
down_revision = 'ec00b5636e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
