"""fixed-merge

Revision ID: 9c1b74bee70c
Revises: bb3911bcebf0
Create Date: 2023-03-07 15:42:32.821403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1b74bee70c'
down_revision = 'bb3911bcebf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
