"""add columns to KyleCart

Revision ID: a6bc502499a7
Revises: 9c1b74bee70c
Create Date: 2023-03-09 14:40:46.873344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bc502499a7'
down_revision = '9c1b74bee70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyle_id', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_entry', sa.String(), nullable=True),
    sa.Column('date_of_adoption', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kyle_id'], ['kyle_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    pass
