"""KyleCart table

Revision ID: bb3911bcebf0
Revises: 3b7337331f37
Create Date: 2023-03-07 15:32:31.962228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3911bcebf0'
down_revision = '3b7337331f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyle_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kyle_id'], ['kyle_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyle_carts')
    # ### end Alembic commands ###
