"""add columns to KyleCart

Revision ID: eec32726f058
Revises: bb3911bcebf0
Create Date: 2023-03-09 15:01:58.256314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec32726f058'
down_revision = 'bb3911bcebf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyle_carts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('kyle_carts', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('kyle_carts', sa.Column('superpower', sa.String(), nullable=True))
    op.add_column('kyle_logs', sa.Column('first_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyle_logs', 'first_name')
    op.drop_column('kyle_carts', 'superpower')
    op.drop_column('kyle_carts', 'last_name')
    op.drop_column('kyle_carts', 'first_name')
    # ### end Alembic commands ###
